In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [ ]:
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX= torch.tensor([[8,9],
                      [2,3]])
MATRIX

tensor([[8, 9],
        [2, 3]])

In [ ]:
TENSOR =torch.tensor([[[1,2,3],
                      [3,4,5],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.0503, 0.9702, 0.1398, 0.2465],
        [0.9131, 0.7705, 0.3765, 0.8517],
        [0.7326, 0.6837, 0.1749, 0.2750]])

In [ ]:
torch.rand(3,3)

tensor([[0.3630, 0.2094, 0.1190],
        [0.8346, 0.4368, 0.7102],
        [0.9129, 0.1266, 0.7377]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.range(0,10)

<ipython-input-17-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.range(start=1, end=11 ,step=1)

<ipython-input-18-a47f9df4fd6e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=1, end=11 ,step=1)


In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=None,
                               divice=None,
                               requires_grad=flase)
float_32_tensor

NameError: ignored

In [ ]:
float_32_tensor.dtype

NameError: ignored

In [ ]:
 tensor = torch.tensor([1,2,3])
 tensor+100

tensor([101, 102, 103])

In [ ]:
  print (f"{tensor * tensor}")

tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range ( len(tensor)):
  value += tensor [ i ] * tensor [i]
  print (value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 2.23 ms, sys: 40 µs, total: 2.27 ms
Wall time: 2.37 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 47 µs, sys: 9 µs, total: 56 µs
Wall time: 51.7 µs


tensor(14)

In [ ]:
tensor @tensor


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.max()

(tensor(0), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),

(tensor(45.),)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmax

<function Tensor.argmax>

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped , x_reshaped.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x ,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1.0 ,8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
Random_seed =42
torch.manual_seed(Random_seed)
random_tensor_c =torch.rand(3,4)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c ==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.cuda.is_available()

False

In [ ]:
device= "cuda" if torch.cuda.is_available() else"cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

In [ ]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1., 2., 3., 4., 5., 6., 7.])